
trigger:
     - master
  
pr:
- master

variables:
  appDir: VirtualClinicFrontEnd

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: node install
  inputs:
    versionSpec: '14.x'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDir)

- script: npx ng build --prod
  displayName: ng build
  workingDirectory: $(appDir)

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(c0f22405-d59c-4823-bfa1-dce6612cb9b8)'
    appType: 'webApp'
    WebAppName: 'virtual-clinic'
    packageForLinux: '$(appDir)/dist/$(appDir)'