# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
 branches:
   include:
     - master


variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  apiFolder: './VirtualClinic/VirtualClinic.Api'

steps:
- task: UseDotNet@2
  displayName: 'get 2.0 SDK for sonar'
  inputs:
    packageType: 'sdk'
    version: '2.0.x'

#sonar settings
- task: SonarCloudPrepare@1
  displayName: 'Sonar Prepare'
  inputs:
    SonarCloud: 'azure backend'
    organization: '2011-nov02-net'
    scannerMode: 'MSBuild'
    projectKey: '2011-nov02-net_VirtualClinic-Project2'
    projectName: '2011-nov02-net_VirtualClinic-Project2'
    extraProperties: 'sonar.exclusions=**/lib/**'


- task: UseDotNet@2
  displayName: 'get sdk for build'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
  

- script: dotnet publish  $(apiFolder) --configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/publish
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet Test Build- $(buildConfiguration)'
  inputs:
    command: 'test'
    projects: '$(System.DefaultWorkingDirectory)/VirtualClinic/VirtualClinic.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Unit Tests'

- task: SonarCloudAnalyze@1
  displayName: 'Sonar Cloud - Run'

- task: SonarCloudPublish@1
  displayName: 'Sonar Cloud - Timeout'
  inputs:
    pollingTimeoutSec: '300'

#publish artifact
- publish:  $(System.DefaultWorkingDirectory)/publish
  displayName: 'publish artifact'
  artifact: BuildAppArtifact

- task: AzureRmWebAppDeployment@4
  displayName: "azure app service deploy backend"
  condition: and( succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(e92a324b-9577-4df8-b544-5189c2ff2bbb)'
    appType: 'webApp'
    WebAppName: 'virtual-clinic-backend'
    packageForLinux: $(System.DefaultWorkingDirectory)/publish
