# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - VirtualClinic
      - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
  workingDirectory: VirtualClinic

- script: dotnet test --no-build --configuration $(buildConfiguration)
  displayName: 'dotnet test'
  workingDirectory: VirtualClinic